export const GALLERY_REVALIDATE_SECONDS = 86400;

export const WIKIMEDIA_GALLERY_QUERIES = [
    '"Ivan Sirko"',
    '"Іван Сірко"',
    '"Иван Сирко"',
    '"Sirko by Repin"',
    '"Ivan Sirko Repin"',
    '"Іван Сірко Рєпін"',
    '"Reply of the Zaporozhian Cossacks"',
    '"Zaporozhian Cossacks Repin"',
    '"Ivan Sirko monument"',
    '"Ivan Sirko grave"',
];

export const MUSEUM_GALLERY_QUERIES = [
    "Ivan Sirko",
    "Sirko",
    "Zaporozhian Cossacks Repin",
    "Reply of the Zaporozhian Cossacks",
];

export const GALLERY_POSITIVE_KEYWORDS = [
    "ivan sirko",
    "іван сірко",
    "ivan dmytrovych sirko",
    "атаман сірко",
    "сірко",
    "сирко",
    "sirko",
    "repin",
    "рєпін",
    "ріпин",
    "zaporozhian cossacks",
    "zaporizhian cossacks",
    "запорож",
    "reply of the zaporozhian cossacks",
    "the zaporozhye cossacks",
];

export const GALLERY_BLOCKED_KEYWORDS = [
    "alligator",
    "ballet",
    "beggar",
    "burger of calais",
    "portrait of ross",
    "anne thackeray",
    "bust of a woman",
    "woman",
    "girl",
    "boy named",
    "american",
    "french",
    "festival",
    "фестиваль",
    "donetsk",
    "донецьк",
    "culture and life",
    "газета",
    "newspaper",
    "combined resolve",
    "drone",
    "military brigade",
    "image detail",
    "detail 1",
    "detail 2",
    "detail 3",
    "detail 4",
    "detail 5",
    "detail 6",
    "detail 7",
    "detail 8",
    "detail 9",
    "map",
    "карта",
    "stamp",
    "postmark",
    "coin",
    "монета",
    "banknote",
    "банкнота",
    "logo",
    "svg",
    "flag",
    "icon",
    "seal",
    "печатка",
    "coat of arms",
    "герб",
];