export const GALLERY_REVALIDATE_SECONDS = 86400;

export const WIKIMEDIA_GALLERY_QUERIES = [
    '"Ivan Sirko"',
    '"Іван Сірко"',
    '"Sirko by Repin"',
    '"Reply of the Zaporozhian Cossacks"',
    '"Zaporozhian Cossacks Repin"',
    '"Ivan Sirko monument"',
    '"Ivan Sirko grave"',
];

export const MUSEUM_GALLERY_QUERIES = [
    "Cossack portrait",
    "Cossack cavalry",
    "Cossack soldier",
];

export const GALLERY_BLOCKED_KEYWORDS = [
    "festival",
    "фестиваль",
    "donetsk",
    "донецьк",
    "culture and life",
    "газета",
    "newspaper",
    "combined resolve",
    "image detail",
    "detail 1",
    "detail 2",
    "detail 3",
    "detail 4",
    "detail 5",
    "detail 6",
    "detail 7",
    "detail 8",
    "detail 9",
    "map",
    "карта",
    "stamp",
    "postmark",
    "coin",
    "монета",
    "banknote",
    "банкнота",
    "logo",
    "svg",
    "flag",
    "icon",
    "seal",
    "печатка",
    "coat of arms",
    "герб",
];

export const GALLERY_ALLOWED_KEYWORDS = [
    "sirko",
    "сірко",
    "сирко",
    "repin",
    "рєпін",
    "ріпин",
    "zaporozhian",
    "zaporizhian",
    "запорож",
    "cossack",
    "козак",
    "otaman",
    "отаман",
    "grave",
    "могила",
    "monument",
    "памятник",
    "пам'ятник",
    "portrait",
    "портрет",
];