export const GALLERY_REVALIDATE_SECONDS = 86400;

export const WIKIMEDIA_GALLERY_QUERIES = [
    '"Ivan Sirko"',
    '"Іван Сірко"',
    '"Иван Сирко"',
    '"Sirko by Repin"',
    '"Ivan Sirko Repin"',
    '"Іван Сірко Рєпін"',
    '"Reply of the Zaporozhian Cossacks"',
    '"Zaporozhian Cossacks Repin"',
    '"Ivan Sirko monument"',
    '"Ivan Sirko grave"',
];

export const GALLERY_POSITIVE_KEYWORDS = [
    "ivan sirko",
    "іван сірко",
    "ivan dmytrovych sirko",
    "атаман сірко",
    "сірко",
    "сирко",
    "sirko",
    "repin",
    "рєпін",
    "ріпин",
    "zaporozhian cossacks",
    "zaporizhian cossacks",
    "запорож",
    "reply of the zaporozhian cossacks",
    "the zaporozhye cossacks",
    "grave",
    "могила",
    "monument",
    "памятник",
    "пам'ятник",
    "bust of ivan sirko",
];

export const GALLERY_BLOCKED_KEYWORDS = [
    "festival",
    "фестиваль",
    "donetsk",
    "донецьк",
    "culture and life",
    "газета",
    "newspaper",
    "combined resolve",
    "drone",
    "military brigade",
    "image detail",
    "detail",
    "map",
    "карта",
    "stamp",
    "postmark",
    "coin",
    "монета",
    "banknote",
    "банкнота",
    "logo",
    "svg",
    "flag",
    "icon",
    "seal",
    "печатка",
    "coat of arms",
    "герб",
];