import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {cookies} from "next/headers";

import "./globals.css";
import {LanguageProvider} from "@/src/context";
import {SiteShell} from "@/src/components/layout";
import {getValidLanguage} from "@/src/helpers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Ivan Sirko",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const initialLang = getValidLanguage(cookieStore.get("lang")?.value);

    return (
        <html
            lang={initialLang}
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
        <body className="min-h-full">
        <LanguageProvider initialLang={initialLang}>
            <SiteShell>{children}</SiteShell>
        </LanguageProvider>
        </body>
        </html>
    );
}
